### ISSUE TITLE
Angular 9 error

### ISSUE THREAD

**Issue by emko** [xipheCom/ngrx-batch-action-reducer#6]
I  can't figure out how to get it to work with Angular 9 after Register enableBatchReducer as metareducer  i get this error.

> ERROR in node_modules/ngrx-batch-action-reducer/dist/index.d.ts:12:1 - error TS-991010: Value at position 1 in the NgModule.imports of AppModule is not a class   

12 export declare function enableBatchReducer<S>(reduce: ActionReducer<S>): ActionReducer<S>;

>

**Comment by progral** [comment]
Have you a playground for this? Will have a look next week.

**Comment by krambono** [comment]
Personally, I don't have any problem with the 9.1.11 angular version.
